#!/bin/sh

function usage {
   echo "usage: "
   echo "   `basename $0` <backup-dir> <bitbucket-acct> <bitbucket-user> <bitbucket-password>"
   exit 1
}

if [ $# -lt 4 ]; then
   usage
fi

dir=$1
acct=$2
user=$3
pass=$4

tn=/tmp/bb$$

cat <<eos >$tn.py
import sys
import json

s = ''.join(sys.stdin.readlines())
x = json.loads(s)

u = x['user']['username']
rs = x['repositories']
for r in rs:
  n = r['name']
  w = r['has_wiki']
  print("git-backup-repositories clone \"git@bitbucket.org:"+u+"/"+n+".git\" \""+u+"/"+n+".git\"")
  if w:
     print("git-backup-repositories clone \"git@bitbucket.org:"+u+"/"+n+".git/wiki\" \""+u+"/"+n+".wiki.git\"")
eos

cd "$1"
curl -s -u $user:$pass https://api.bitbucket.org/1.0/users/$acct | python $tn.py | sh
rm -f $tn.py

exit 0;
