#!/bin/sh

function usage {
   echo "usage: `basename $0` backup-dir"
   exit 1
}

function update_repo {
   ( 
   dir="$1"
   cd "$dir";
   if [ $? -ne 0 ]; then
      echo "ERROR: Cannot 'cd' to '$dir'" >&2
      return 1
   fi
   git remote update 2>&1 >/dev/null
   if [ $? -ne 0 ]; then
      echo "ERROR: 'git remote update' failed in '$dir'" >&2
      return 1
   fi
   )
}

if [ $# -ne 1 ]; then
   usage
fi
dir=$1

for o in $dir/*; do
   for r in $o/*.git; do 
      echo "Updating $r..."
      update_repo $r
   done
done
