#!/bin/sh -e

OS=${OS:-`uname`}
rev="${1-HEAD}"
pattern="${2-*}"
prefix="${3-.}"

#echo "git-update-timestamp: '$OS', '$rev', '$pattern', '$prefix'"

get_file_rev() {
    git rev-list "$rev" "$1" | head -n 1
}

report() {
    echo "$2 $3/$1"
}

skip() {
    echo "Missing         $2/$1"
}


if   [ "$OS" = 'Linux' ]
then
    update_file_timestamp() {
        target="$2/$1"
        if [ -e "$target" ]; then
           file_time=`git show --pretty=format:%ai --abbrev-commit "$(get_file_rev "$1")" | head -n 1`
           touch -d "$file_time" "$target"
           report "$1" "$file_time" "$2"
        else 
           skip "$1" "$2"
        fi
    }
elif [ "$OS" = 'FreeBSD' ]
then
    update_file_timestamp() {
        target="$2/$1"
        if [ -e "$target" ]; then
           file_time=`date -r "$(git show --pretty=format:%at --abbrev-commit "$(get_file_rev "$1")" | head -n 1)" '+%Y%m%d%H%M.%S'`
           touch -h -t "$file_time" "$target"
           report "$1" "$file_time" "$2"
        else
           skip "$1" "$2"
        fi
    }
elif [ "$OS" = 'Darwin' ]
then
    update_file_timestamp() {
        target="$2/$1"
        if [ -e "$target" ]; then
           file_time=`date -j -f '%s' "$(git show --pretty=format:%at --abbrev-commit "$(get_file_rev "$1")" | head -n 1)" '+%Y%m%d%H%M.%S'`
           #stat -t '%Y%m%d%H%M.%S' -f "stat1: %Sa %Sm %Sc %i %N" "$target"
           touch -t "$file_time" "$target"
           report "$1" "$file_time" "$2"
           #stat -t '%Y%m%d%H%M.%S' -f "stat2: %Sa %Sm %Sc %i %N" "$target"
        else 
           skip "$1" "$2"
        fi
    }
else
    echo "error: timestamp fix not implemented for $OS" >&2
    exit 1
fi

for file in `git ls-files "$pattern"`
do
    update_file_timestamp "$file" "$prefix"
done

